import { router, json, error } from '@appdeploy/sdk';

type Rpc={jsonrpc?:string;id?:string|number|null;method?:string;params?:Record<string,unknown>};
const NOAUTH=[{type:'noauth'}];
const SERVER_INFO={name:'grill-chat',title:'GRILL Chat',version:'5.0.0'};
const MODERN_VERSION='2026-07-28';
const LEGACY_VERSIONS=new Set(['2025-11-25','2025-06-18','2025-03-26']);
const MODERN_METHODS=new Set(['server/discover','ping','tools/list','resources/list','resources/read','tools/call']);
const INSTRUCTIONS='Use GRILL only when explicitly invoked. GRILL stress-tests a plan, architecture, design, product decision, strategy, specification, or idea through dependency-ordered questioning. Research facts with available read-capable tools instead of asking the user when possible. Keep the session read-only until Shared Understanding is explicitly confirmed.';
const DIRECTIVE=`GRILL MODE — ACTIVE\n\nRun a rigorous decision stress-test in the current conversation. Build and maintain a decision tree. Separate researchable FACTS from user-owned DECISIONS. Work in rounds using the current FRONTIER: unresolved decisions whose prerequisites are already settled. Ask only the current frontier; dependent questions belong to later rounds. For every decision question, give a concise recommendation and rationale. After each answer, update the tree, detect contradictions, verify newly resolvable facts with available read-capable tools/context, then recompute the frontier. Challenge hidden assumptions, contradictory requirements, missing success/failure criteria, unclear ownership, irreversible choices, dependencies, unnecessary complexity, security/privacy, operational burden, migration problems, edge cases, scaling assumptions, adoption friction, and organizational constraints. While GRILL is active remain read-only: do not execute the plan or mutate external systems. Finish only when no material frontier remains. Then present Shared Understanding with Objective, Decisions, Constraints, Verified facts, Assumptions, Risks, Resulting approach, Remaining uncertainty, and ask for explicit confirmation before leaving GRILL. Controls: status, tree, assumptions, facts, risks, resume, stop, approve.`;
const OUTPUT={type:'object',properties:{mode:{type:'string',const:'grill'},command:{type:'string'},readOnly:{type:'boolean'},request:{type:'string'}},required:['mode','command','readOnly','request'],additionalProperties:false};
const grillTool={name:'grill',title:'GRILL',description:'Explicitly enter GRILL mode to stress-test a plan, decision, architecture, design, strategy, specification, or idea through dependency-ordered questioning. Use only when the user explicitly invokes GRILL or asks to be grilled. Read-only until shared understanding is approved.',inputSchema:{type:'object',properties:{request:{type:'string',description:'The plan, idea, decision, or GRILL control request.'},command:{type:'string',enum:['start','status','tree','assumptions','facts','risks','resume','stop','approve'],default:'start'}},required:['request'],additionalProperties:false},outputSchema:OUTPUT,securitySchemes:NOAUTH,annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{securitySchemes:NOAUTH,ui:{visibility:['model']},'openai/toolInvocation/invoking':'Starting GRILL…','openai/toolInvocation/invoked':'GRILL ready'}};
const metaResult=(result:Record<string,unknown>)=>({...result,resultType:'complete',_meta:{...((result._meta as Record<string,unknown>)||{}),'io.modelcontextprotocol/serverInfo':SERVER_INFO}});
const call=(a:Record<string,unknown>)=>{const command=String(a.command||'start');const request=String(a.request||'');let text=DIRECTIVE;if(command==='stop')text='GRILL MODE — STOP. Exit GRILL without implementation. Preserve settled decisions in the conversation.';else if(command==='approve')text='GRILL MODE — APPROVED. Treat the latest Shared Understanding as authoritative, exit GRILL, and implement only if separately requested.';else if(command!=='start'&&command!=='resume')text+=`\n\nCURRENT CONTROL COMMAND: ${command}. Perform that control view from the decision state already present in the conversation, then remain in GRILL mode.`;const structuredContent={mode:'grill',command,readOnly:command!=='approve'&&command!=='stop',request};return{structuredContent,content:[{type:'text',text}]}};
const rpc=async(r:Rpc)=>{const id=r.id??null;try{if(r.method==='server/discover')return{jsonrpc:'2.0',id,result:metaResult({supportedVersions:[MODERN_VERSION],capabilities:{tools:{},resources:{}},instructions:INSTRUCTIONS,ttlMs:60000,cacheScope:'public'})};if(r.method==='initialize'){const requested=String((r.params&&r.params.protocolVersion)||'2025-11-25');const legacy=['2025-11-25','2025-06-18','2025-03-26'];const protocolVersion=legacy.includes(requested)?requested:'2025-11-25';return{jsonrpc:'2.0',id,result:{protocolVersion,capabilities:{tools:{listChanged:false},resources:{listChanged:false}},serverInfo:SERVER_INFO,instructions:INSTRUCTIONS}};}if(r.method==='ping')return{jsonrpc:'2.0',id,result:metaResult({})};if(r.method==='tools/list')return{jsonrpc:'2.0',id,result:metaResult({tools:[grillTool],ttlMs:60000,cacheScope:'public'})};if(r.method==='resources/list')return{jsonrpc:'2.0',id,result:metaResult({resources:[],ttlMs:60000,cacheScope:'public'})};if(r.method==='resources/read')return{jsonrpc:'2.0',id,error:{code:-32002,message:'Resource not found'}};if(r.method==='tools/call'){const p=(r.params||{}) as {name?:string;arguments?:Record<string,unknown>};const name=String(p.name||'');if(name!=='grill')return{jsonrpc:'2.0',id,result:metaResult({isError:true,content:[{type:'text',text:'GRILL tool error: Unknown tool '+name}]})};try{return{jsonrpc:'2.0',id,result:metaResult(call(p.arguments||{}))}}catch(e){const message=e instanceof Error?e.message:String(e);console.error('MCP_TOOL_ERROR',JSON.stringify({tool:name,message}));return{jsonrpc:'2.0',id,result:metaResult({isError:true,content:[{type:'text',text:'GRILL tool error: '+message}]})}}}if(r.method==='notifications/initialized')return null;return{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found: '+r.method}}}catch(e){return{jsonrpc:'2.0',id,error:{code:-32000,message:e instanceof Error?e.message:String(e)}}}};

export const handler=router({
  'GET /api/_healthcheck':[async()=>json({message:'Success'})],
  'GET /api/mcp':[async()=>({statusCode:405,headers:{Allow:'POST','Content-Type':'application/json'},body:JSON.stringify({error:'SSE stream not offered; use POST for MCP JSON-RPC.'})})],
  'POST /api/mcp':[async({body,event})=>{if(!body||typeof body!=='object'||Array.isArray(body))return error('Invalid JSON-RPC request',400);const request=body as Rpc;const raw=(event?.headers||{}) as Record<string,unknown>;const headers=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k.toLowerCase(),String(v??'')]));const protocol=headers['mcp-protocol-version']||'';const method=String(request.method||'');const params=(request.params||{}) as Record<string,unknown>;const bodyMeta=(params._meta||{}) as Record<string,unknown>;const bodyVersion=String(bodyMeta['io.modelcontextprotocol/protocolVersion']||'');const modern=protocol===MODERN_VERSION||bodyVersion===MODERN_VERSION||method==='server/discover';console.warn('MCP_REQUEST',JSON.stringify({method,protocol:protocol||null,bodyVersion:bodyVersion||null,mcpMethod:headers['mcp-method']||null,mcpName:headers['mcp-name']||null,userAgent:headers['user-agent']||null,modern}));const jsonRpcError=(status:number,code:number,message:string,data?:unknown)=>({statusCode:status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify({jsonrpc:'2.0',id:request.id??null,error:{code,message,...(data===undefined?{}:{data})}})});if(modern){if(protocol!==MODERN_VERSION||bodyVersion!==MODERN_VERSION)return jsonRpcError(400,-32020,'Header mismatch: MCP-Protocol-Version and request _meta protocolVersion must both be 2026-07-28');if(headers['mcp-method']!==method)return jsonRpcError(400,-32020,'Header mismatch: Mcp-Method does not match JSON-RPC method');const expectedName=method==='tools/call'?String(params.name||''):method==='resources/read'?String(params.uri||''):'';if(expectedName&&headers['mcp-name']!==expectedName)return jsonRpcError(400,-32020,'Header mismatch: Mcp-Name does not match request body');if(!MODERN_METHODS.has(method))return jsonRpcError(404,-32601,'Method not found: '+method);const response=await rpc(request);return response===null?{statusCode:202,headers:{'Cache-Control':'no-store'},body:''}:{statusCode:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(response)}}if(method!=='initialize'&&protocol&&!LEGACY_VERSIONS.has(protocol))return jsonRpcError(400,-32000,'Unsupported MCP protocol version',{supportedVersions:[MODERN_VERSION,...LEGACY_VERSIONS]});const response=await rpc(request);return response===null?{statusCode:202,headers:{'Cache-Control':'no-store'},body:''}:{statusCode:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(response)}}]
});
